# Generated by Django 4.2.1 on 2023-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.CharField(default='lions', max_length=100),
        ),
    ]
