# Generated by Django 4.2.1 on 2023-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gallery_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=70)),
                ('mini_title', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('tag', models.CharField(default='Maasai Mara', max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
