# Generated by Django 4.2.1 on 2023-06-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Destination',
            new_name='thedestination',
        ),
        migrations.AddField(
            model_name='destination',
            name='paragraph',
            field=models.TextField(default='Maasai Mara'),
        ),
    ]
