# Generated by Django 4.2.1 on 2023-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_destination_destination_thedestination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='paragraph',
            new_name='paragraph1',
        ),
        migrations.AddField(
            model_name='destination',
            name='paragraph2',
            field=models.TextField(default='Maasai Mara'),
        ),
        migrations.AddField(
            model_name='destination',
            name='paragraph3',
            field=models.TextField(default='Maasai Mara'),
        ),
        migrations.AddField(
            model_name='destination',
            name='paragraph4',
            field=models.TextField(default='Maasai Mara'),
        ),
    ]
