# Generated by Django 4.2.4 on 2023-12-04 08:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tag',
            field=models.CharField(choices=[('birds', 'birds'), ('wildebeest', 'wildebeest'), ('buffalo', 'buffalo'), ('rhinos', 'rhinos'), ('elephants', 'elephants'), ('lions', 'lions'), ('leopards', 'leopards'), ('Maasai Mara', 'Maasai Mara')], default='lions', max_length=100),
        ),
    ]
