# Generated by Django 5.0 on 2023-12-18 19:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='post',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
