# Generated by Django 5.0 on 2023-12-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_body_post_body1_post_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tag',
            field=models.CharField(choices=[('birds', 'birds'), ('wildebeest', 'wildebeest'), ('buffalo', 'buffalo'), ('rhinos', 'rhinos'), ('elephants', 'elephants'), ('lions', 'lions'), ('leopards', 'leopards'), ('Maasai Mara', 'Maasai Mara'), ('Tsavo', 'Tsavo'), ('Olpejeta', 'Olpejeta')], default='lions', max_length=100),
        ),
    ]
